### ISSUE TITLE
Rails 4 not using Remotipart to remotely submit form

### ISSUE THREAD

**Issue by tomprats** [JangoSteve/remotipart#109]
I asked a question on stackoverflow: http://stackoverflow.com/questions/24554335/rails-4-not-using-remotipart-to-remotely-submit-form

Essentially it looks like remotipart isn't being triggered. I followed the setup and everything but no luck. Let me know if you need any more details than are in the question!

**Comment by AmitPatel-BoTreeConsulting** [comment]
I am facing same issue with Rails 4.2.4

@tomprats @create-renegr I tried https://github.com/nouira/jquery-form-rails but it doesn't work. It submits the page instead of remotely sending request by ajax if I choose a file.

Here how I used `jquery-form-rails`

1. Add following to `Gemfile`

  `gem 'jquery-form-rails' `

2. `bundle install`

3.  Add following to `application.js`

  `//= rquire 'jquery.form'`

Am I missing something?

**Comment by kamal-github** [comment]
I am also facing the same issue with Rails 4.2, Is it fixed yet? or any solution please.

**Comment by vincentkedison** [comment]
I'm also facing the same issue with Rails 4.2.5.2. Please help. Thankyou.

**Comment by Frank004** [comment]
same here +1

**Comment by kamal-github** [comment]
I think this gem is not active, as no body respond 👎

**Comment by Frank004** [comment]
yes I'm moving to jquery-upload-file to see I can make it work

**Comment by kamal-github** [comment]
@Frank004 cool!

**Comment by vincentkedison** [comment]
Thankyou @Frank004.
