### ISSUE TITLE
html escape

### ISSUE THREAD

**Issue by tnedlacer** [JangoSteve/remotipart#20]
Hi. I write the code so can not speak English.

controller

``` ruby
render :js => "alert('& &amp; > &gt; < &lt; \" &quot;')"
```

response.body

``` html
<textarea data-type="text/javascript" response-code="200">alert('&amp; &amp; &gt; &gt; &lt; &lt; &quot; &quot;')</textarea>
```

alert

```
& & > > < < " "
```

edit lib/remotipart/render_overrides.rb

``` ruby
# response.body = %{<textarea data-type=\"#{content_type}\" response-code=\"#{response.response_code}\">#{escape_once(response.body)}</textarea>}
response.body = %{<textarea data-type=\"#{content_type}\" response-code=\"#{response.response_code}\">#{ERB::Util.h(response.body)}</textarea>}
```

response.body

``` html
<textarea data-type="text/javascript" response-code="200">alert('&amp; &amp;amp; &gt; &amp;gt; &lt; &amp;lt; &quot; &amp;quot;')</textarea>
```

alert

```
& &amp; > &gt; < &lt; " &quot;
```

**Comment by ioev** [comment]
Just a heads up that this isn't fixed.  I'm having the same problem with a single quote in a js.erb file returned after a remotipart iframe submission.  It seems like the root problem is that jQuery gets confused by the content type (because the response starts with "<head>" and contains other html tags, assumes it is html/text, and then escapes it as such, replacing &#39; with a single quote and breaking the javascript.  In my case, a response containing something like:

$('<div>Steve&#39;s</div>')  became $('<div>Steve's</div>')

I fixed the problem by changing my surrounding single quotes to double quotes, but in that case a double quote causes the same issue.

Remotipart version: 1.3.1
jQuery 1.12.1
